dist: trusty
sudo: required
language: cpp
compiler: gcc

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-7 doxygen graphviz libboost-test1.54-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90 
  
script:
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - cmake --build .
  - cmake --build . --target test
  - doxygen Doxyfile  
  
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local_dir: html
    on:
     branch: master
